all:
	javac -classpath ../../../platform/bindings/java/target/diamond-1.0-SNAPSHOT.jar:../../../platform/bindings/java/libs/javacpp.jar Client.java
	javac -classpath ../../../platform/bindings/java/target/diamond-1.0-SNAPSHOT.jar:../../../platform/bindings/java/libs/javacpp.jar Publisher.java
